version: '3'
services:
  wifted-service:
    build: ./
    restart: always
    container_name: wifted-service
    ports:
    - 8080:8080
    depends_on:
    - wifted-database

  wifted-database:
    image: mongo:4.0.2
    container_name: wifted-database
    ports:
    - 27017:27017
    volumes:
    - ./data/db:/data/db
    restart: always